### PR TITLE
cmd/combine: support testnet config

### LINKED ISSUE #2838: Add testnet flags to combine command
# 🎯 Problem to be solved

The current `charon combine` command doesn't support testnet flags and errors like the below:
```
charon-distributed-validator-cluster % docker run -u $(id -u):$(id -g) --rm -v "$(pwd)/:/opt/charon" obolnetwork/charon:v0.19.1-rc1 combine    
12:17:55.905 INFO cmd        Recombining private key shares           {"input_dir": "/opt/charon/.charon/cluster", "output_dir": "/opt/charon/validator_keys"}
12:17:55.918 ERRO cmd        Fatal error: cannot open manifest file: manifest load error: load dag from disk: couldn't load cluster from legacy lock file: cluster lock signature verification failed. Run with --no-verify to bypass verification at own risk: invalid definition: invalid fork version {"name": "node0", "fork_version": "0x10000038"}
        eth2util/network.go:110 .networkFromForkVersion
        eth2util/network.go:115 .ForkVersionToChainID
        cluster/eip712sigs.go:74 .digestEIP712
        cluster/definition.go:182 .VerifySignatures
        cluster/lock.go:145 .VerifySignatures
        cmd/combine/combine.go:268 .verifyLock
        cmd/combine/combine.go:230 .func1
        cluster/manifest/load.go:103 .loadDAGFromLegacyLock
        cluster/manifest/load.go:47 .LoadDAG
        cluster/manifest/load.go:26 .LoadCluster
        cmd/combine/combine.go:229 .loadManifest
        cmd/combine/combine.go:61 .Combine
        cmd/combine.go:51 .newCombineFunc
        cmd/combine.go:28 .func1
        cmd/cmd.go:80 .func1
        main.go:19 .main
```

# 🛠️ Proposed solution

Add testnet flags to the `charon combine` command.

### PR DESCRIPTION
**Pull request by gsora**
Add `--testnet-*` flags to `combine` command.

Users must specify custom network name, chain ID genesis timestamp and fork version as hex string to allow for a custom testnet configuration to work.

category: bug
ticket: #2838 

Closes #2838.

### CODE REVIEW

File: cluster/test_cluster.go [hunk 1]
```diff
@@ -67,7 +67,19 @@ func NewForT(t *testing.T, dv, k, n, seed int, opts ...func(*Definition)) (Lock,
...
 		feeRecipientAddr := testutil.RandomETHAddress()
-		reg := getSignedRegistration(t, rootSecret, feeRecipientAddr, eth2util.Goerli.Name)
+
+		// get the forkHash to retrieve the network name
+		var def Definition
+		for _, opt := range opts {
+			opt(&def)
+		}
+
+		networkName, _ := eth2util.ForkVersionToNetwork(def.ForkVersion)
```
Comment (xenowits) [inline cluster/test_cluster.go:77]:
```suggestion
		networkName, err := eth2util.ForkVersionToNetwork(def.ForkVersion)
		require.NoError(t, err)
```

**Review by xenowits — APPROVED** [review]

File: cluster/test_cluster.go (hunk 1 above)
Comment (gsora) [reply cluster/test_cluster.go:77]: The error is ignored on purpose: if `def.ForkVersion` is empty because it wasn't set with an option function, adding `require.NoError(t, err)` will fail the test erroneously.

Comment (gsora) [reply cluster/test_cluster.go]: Reworked to make use of the error.

**Review by dB2510 — APPROVED** [review]

**Comment by dB2510** [comment]
@gsora we have merge conflicts in this PR.
