### PR TITLE
dkg: exchange sigTypes concurrently

### LINKED ISSUE #2491: Possible race condition in DKG exchanger
# 🐞 Bug Report

### Description

The DKG uses the `exchanger` component for:
```
exhanges partial signatures of lockhash/deposit-data among dkg participants and returns all the partial
BLS signatures of the cluster according to public key of each vallidator.
```

It used to exchange the following signatures:
- `signAndAggDepositData`
- `signAndAggValidatorRegistrations`
- `signAndAggLockHash`

Note that timing in distributed systems can be unintuitive and can follow unexpected sequences.

The code requires all three above "types" to be executed in sequence on each peer. We drop unexpected duty types silently, which could happen in large geo-distributed clusters where Q nodes are close to each other, they might already be done with all three while one need is far away and might receive quorum messages out of order. Silently dropping that and getting stuck.
```
		case peerSet := <-e.sigChan:
			if sigType != peerSet.sigType {
				// Do nothing if duty doesn't match
				continue
			}
			sets[peerSet.pubkey] = peerSet.psigs
		}
```

### Proposed Solution

Refactor exchanger to something like DutyDB with a query API allowing out of order queries and responses.

Oh, and this is another good example of improper error handling. We should have error edabove instead of silently dropping it.

### PR DESCRIPTION
**Pull request by gsora**
Before this commit, calling `exchange()` would listen for new incoming messages and discard everything that didn't carry the expected `sigType`.

In a DKG one node might fall behind the others (for example, while DKG'ing 3000 validator keys) and send `sigTypes` that the other peers have already received threshold for.

This PR makes sure a given instance of `exchanger` will hold onto all messages whose `sigTypes` are specified during its initialization phase.

Calling `exchange()` will return as soon as there are enough messages for the specified `sigType`, but different `sigType`s messages will still be stored and will be returned when requested by means of another `exchange()` call, with a different `sigType` argument.

category: bug
ticket: #2491

Closes #2491.

### CODE REVIEW

File: dkg/exchanger.go [hunk 1]
```diff
@@ -29,6 +34,46 @@ const (
...
+
+	stb.store[sigType][pubKey] = data
+}
+
+// get gets all the core.ParSignedData for a given core.PubKey.
+func (stb *dataByPubkey) get(sigType sigType) map[core.PubKey][]core.ParSignedData {
+	stb.lock.Lock()
+	defer stb.lock.Unlock()
+
+	if len(stb.store[sigType]) == 0 {
```
[the remark this answers is not in the document]
Comment (corverroos) [reply dkg/exchanger.go:64]: optional nit: bool checks are slightly more readable than nil checks

File: dkg/exchanger.go [hunk 2]
```diff
@@ -29,6 +34,46 @@ const (
...
+type sigTypeStore map[sigType]map[core.PubKey][]core.ParSignedData
+
+// dataByPubkey maps a sigType to its map of public key to slice of core.ParSignedData..
+type dataByPubkey struct {
+	store sigTypeStore
+	lock  sync.Mutex
+}
+
+// set sets data for the given sigType and core.PubKey.
+func (stb *dataByPubkey) set(pubKey core.PubKey, sigType sigType, data []core.ParSignedData) {
```
Comment (corverroos) [inline dkg/exchanger.go:47]: can refactor this to a single `sigdatas` parameter

File: dkg/exchanger.go [hunk 3]
```diff
@@ -29,6 +34,46 @@ const (
 	sigValidatorRegistration sigType = 103
 )
 
+// sigTypeStore is a shorthand for a map of sigType to map of core.PubKey to slice of core.ParSignedData.
+type sigTypeStore map[sigType]map[core.PubKey][]core.ParSignedData
+
+// dataByPubkey maps a sigType to its map of public key to slice of core.ParSignedData..
+type dataByPubkey struct {
```
Comment (corverroos) [inline dkg/exchanger.go:41]: personal style: I would not introduce more types. I would just put the lock  and a `map[sigType]sigData` in `exchanger` itself. 

func (e exchanger) set(sigdata) {...}
func (e exchanger) get(sigtype) (sigdata, bool) {...}

But that is just me #lessismore

**Review by corverroos — APPROVED** [review]

**Comment by corverroos** [comment]
LGTM
