### PR TITLE
core/consensus: verify wire justification duties

### LINKED ISSUE #1923: Verify QBFT justifications
# 🐞 Bug Report

### Description

We do not verify QBFT justification messages properly. This could result in replay attacks using previous consensus instance justifications.

Proposed solution:
 - Verify justification duty matches current instance.

### PR DESCRIPTION
**Pull request by gsora**
Fixes OBOL-07.

category: bug
ticket: #1923 

Closes #1923

### CODE REVIEW

File: core/consensus/component.go [hunk 1]
```diff
@@ -362,17 +362,32 @@ func (c *Component) handle(ctx context.Context, _ peer.ID, req proto.Message) (p
...
+		if justification == nil {
 			return nil, false, errors.New("nil justification", z.Any("duty", duty))
 		}
 
-		justPubkey, exists := c.pubkeys[msg.PeerIdx]
+		justDuty := core.DutyFromProto(justification.Duty)
+		if !justDuty.Type.Valid() {
+			return nil, false, errors.New(
+				"invalid consensus justification duty type",
+				z.Str("type", justDuty.Type.String()))
```
Comment (corverroos) [inline core/consensus/component.go:374]: invalid types do not have valid strings, rather use raw int value?

**Review by corverroos — APPROVED** [review]

**Review by corverroos — APPROVED** [review]
