### PR TITLE
eth2util/keystore: order keystores by index

### LINKED ISSUE #2151: Error while combining 1000 distributed keys
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

While using the combine feature of the tool, there is an error prompted and the keys are never combined. This was done for 1000 distributed keys in 4 nodes.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

Place your distributed keys in a folder following the structure as [here](https://docs.obol.tech/docs/int/quickstart/quickstart-combine): 

## 🔥 Error

<pre><code>

ethereum@Ubuntu-2004-focal-64-minimal-hwe:/home/ethereum/charon_playground/charon_keys/cluster7$ docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.15.0 combine --cluster-dir /opt/charon/validators-to-be-combined
14:58:28.425 INFO            Recombining key shares                   {"input_dir": "/opt/charon/validators-to-be-combined", "output_dir": "/opt/charon/validator_keys"}
15:09:06.252 INFO            Recombining key share                    {"validator_number": 346}
Error: generated and lockfile public key for validator DO NOT match
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.4 LTS
  </code>
</pre>

**What version of Charon are you running? (Which release)**

<pre>
  <code>
obolnetwork/charon:v0.15.0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by gsora**
Fixes an error in `cmd/combine` where the i'th combined key was different than expected one if the amount of validator in the lock file is greater than 10.

`filepath.Glob()` orders its input in lexicographical order, so that the following output is obtained:

```
├── keystore-insecure-0.json
├── keystore-insecure-0.txt
├── keystore-insecure-1.json
├── keystore-insecure-1.txt
├── keystore-insecure-10.json
├── keystore-insecure-10.txt
├── keystore-insecure-2.json
├── keystore-insecure-2.txt
```

In this instance, keystore 10 comes before keystore 2.

`cmd/combine` uses the lock file keys order to orchestrate its logic and given the mismatch between that and the `LoadKeys()` output, a key mismatch error will result: `combine` expected key at index 2 to be what's contained in `keystore-insecure-2.json`, but it obtained `keystore-insecure-10.json`.

Ordering the keys path before reading the keystores fixes this issue.

Also added a test in `cmd/combine` which combines 100 validator keys among 4 operators.

category: bug
ticket: #2151

Closes #2151

### CODE REVIEW

File: eth2util/keystore/keystore.go [hunk 1]
```diff
@@ -121,6 +129,40 @@ func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
...
+			err = errors.New("keystore filenames do not match expected pattern")
+			return false
+		}
+
+		firstNumRaw := extractor.FindStringSubmatch(first)[1]
+		secondNumRaw := extractor.FindStringSubmatch(second)[1]
+
+		// PSA: we're avoiding error checking here because the regexp is explicitly expecting
+		// numbers in the first glob, hence Atoi will never fail.
+		firstNum, _ := strconv.Atoi(firstNumRaw)
```
Comment (corverroos) [inline eth2util/keystore/keystore.go:153]: what is the cost of adding an error check here? seems trivial to add and doesn't complicate things much, I'd just add it, then regexp can't bite us later.

Comment (gsora) [reply eth2util/keystore/keystore.go:153]: The cost is insignificant, I can add it.

Although, I would trust the regexp engine to be right... but can *I* be trusted? We'll never know.

if err it is.

File: eth2util/keystore/keystore.go [hunk 2]
```diff
@@ -121,6 +133,104 @@ func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
 	return resp, nil
 }
 
+// LoadKeysSequential returns all secrets stored in dir/keystore-([0-9]*).json 2335 Keystore files
```
Comment (corverroos) [inline eth2util/keystore/keystore.go:136]: EIP-2335 keystore files

File: eth2util/keystore/keystore.go [hunk 3]
```diff
@@ -121,6 +133,104 @@ func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
...
+// using password stored in dir/keystore-([0-9]*).txt.
+// The keystore files are read based on their index, and the returned slice is sorted accordingly.
```
Comment (corverroos) [inline eth2util/keystore/keystore.go:138]: please add something about it returning only sequential 0-N files.

File: eth2util/keystore/keystore.go [hunk 4]
```diff
@@ -121,6 +133,104 @@ func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
...
+func LoadKeysSequential(dir string) ([]tbls.PrivateKey, error) {
+	return loadFiles(dir, "keystore-*.json", func(files []string) ([]string, error) {
```
Comment (corverroos) [inline eth2util/keystore/keystore.go:140]: why pass in glob if it is the same in both instances, `"keystore-*.json"`?

File: eth2util/keystore/keystore.go [hunk 5]
```diff
@@ -121,6 +133,104 @@ func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
...
+			}
+		}
+
+		return newFiles, nil
+	})
+}
+
+// LoadKeys returns all secrets stored in dir/keystore-*.json 2335 Keystore files
+// using password stored in dir/keystore-*.txt.
+func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
```
Comment (corverroos) [inline eth2util/keystore/keystore.go:175]: please add a note that the order is lexicographic

File: eth2util/keystore/keystore.go [hunk 6]
```diff
@@ -121,6 +133,104 @@ func LoadKeys(dir string) ([]tbls.PrivateKey, error) {
...
+	var sortErr error
+
+	idxSet := make(map[int]struct{})
+
+	sort.Slice(files, func(i, j int) bool {
+		first := strings.TrimPrefix(files[i], prefix)
+		second := strings.TrimPrefix(files[j], prefix)
+
+		if !extractor.MatchString(first) || !extractor.MatchString(second) {
+			sortErr = errors.New("keystore filenames do not match expected pattern")
```
Comment (corverroos) [inline eth2util/keystore/keystore.go:194]: please split this check into two and add expected pattern and actual filename as error param for improved UX and debugging : 

`errors.New("keystore filenames do not match expected pattern 'keystore-%d.json'", z.Str("filename", first)`

File: cmd/combine/combine.go [hunk 7]
```diff
@@ -79,16 +79,21 @@ func Combine(ctx context.Context, inputDir, outputDir string, force bool, opts .
 	var combinedKeys []tbls.PrivateKey
 
 	for idx, pkSet := range privkeys {
+		if len(pkSet) != len(lock.Operators) {
+			return errors.New(
+				"amount of private keys read doesn't match the current validator index",
```
Comment (corverroos) [inline cmd/combine/combine.go:84]: nit: `not all private keys found for validator`

File: cmd/combine/combine.go [hunk 8]
```diff
@@ -79,16 +79,21 @@ func Combine(ctx context.Context, inputDir, outputDir string, force bool, opts .
...
+				z.Int("validator_number", idx),
```
Comment (corverroos) [inline cmd/combine/combine.go:85]: `validator_index`

File: cmd/combine/combine.go [hunk 9]
```diff
@@ -79,16 +79,21 @@ func Combine(ctx context.Context, inputDir, outputDir string, force bool, opts .
...
+				z.Int("required_amount", len(lock.Operators)),
```
Comment (corverroos) [inline cmd/combine/combine.go:86]: ni: "expected" and "actual"

File: cmd/combine/combine.go [hunk 10]
```diff
@@ -66,7 +66,7 @@ func Combine(ctx context.Context, inputDir, outputDir string, force bool, opts .
 	privkeys := make(map[int][]tbls.PrivateKey)
 
 	for _, pkp := range possibleKeyPaths {
-		secrets, err := keystore.LoadKeys(pkp)
+		secrets, err := keystore.LoadKeysSequential(pkp)
 		if err != nil {
 			return errors.Wrap(err, "cannot load keystore", z.Str("path", pkp))
```
Comment (corverroos) [inline cmd/combine/combine.go:71]: nit: `cannot load private keys`

File: cmd/combine/combine.go [hunk 11]
```diff
@@ -79,16 +79,21 @@ func Combine(ctx context.Context, inputDir, outputDir string, force bool, opts .
...
+		if len(pkSet) != len(lock.Operators) {
+			return errors.New(
+				"amount of private keys read doesn't match the current validator index",
+				z.Int("validator_number", idx),
+				z.Int("required_amount", len(lock.Operators)),
+				z.Int("got", len(pkSet)),
+			)
+		}
+
 		log.Info(ctx, "Recombining key share", z.Int("validator_number", idx))
```
Comment (corverroos) [inline cmd/combine/combine.go:91]: suggest aligning the language throughout this command: key vs key share vs private key vs private key share

Comment (corverroos) [reply cmd/combine/combine.go:91]: suggest: `private key share`

File: eth2util/keystore/keystore.go (hunk 5 above)
Comment (corverroos) [inline eth2util/keystore/keystore.go:175]: please also add tests for other non charon filenames, `keystore-foo.json, keystore-bar-1,json, keystore-bar-2.json, keystore-bar-10.json`, asserting returned order. This prevents us breaking the API inadvertantly.

File: eth2util/keystore/keystore_internal_test.go [hunk 12]
```diff
@@ -0,0 +1,79 @@
...
+				"/keystore-insecure-fail.json",
+				"/keystore-insecure-failtoo.json",
+			},
+			nil,
+			require.Error,
+		},
+		{
+			"single file path yields the exact same thing",
+			[]string{
+				"/keystore-0.json",
```
Comment (corverroos) [inline eth2util/keystore/keystore_internal_test.go:62]: add a test for missing 0 index 🙏

**Review by corverroos — APPROVED** [review]

File: eth2util/keystore/keystore_internal_test.go (hunk 12 above)
Comment (gsora) [reply eth2util/keystore/keystore_internal_test.go:62]: Already tested in `TestStoreLoadKeysAllNonSequentialIdx`.
