### PR TITLE
cmd: fix `create cluster` regression

### LINKED ISSUE #2444: Missing flags error on create cluster command
# 🎯 Problem to be solved
create cluster command throws an error about missing --nodes, --num-validators flags when --definition-file is passed.

Image

# 🛠️ Proposed solution

### PR DESCRIPTION
**Pull request by gsora**
After the `create cluster` refactor a couple PR's back, definition file was essentially ignored.

This PR restores that functionality back.

category: bug
ticket: #2444

Closes #2444

### CODE REVIEW

File: cmd/createcluster.go [hunk 1]
```diff
@@ -152,22 +147,38 @@ func runCreateCluster(ctx context.Context, w io.Writer, conf clusterConfig) erro
 		if err != nil {
 			return err
 		}
+
+		defWAddrs := def.WithdrawalAddresses()
+		defFAddrs := def.FeeRecipientAddresses()
+
+		if len(defFAddrs) != 0 {
```
Comment (corverroos) [inline cmd/createcluster.go:154]: I'd stick to "definition overrides all other configuration flags". So It doesn't state "non-zero values in the definition overrides any provided in other flags."

**Review by corverroos — CHANGES_REQUESTED** [review]

File: cmd/createcluster.go [hunk 2]
```diff
@@ -152,22 +147,30 @@ func runCreateCluster(ctx context.Context, w io.Writer, conf clusterConfig) erro
 		if err != nil {
 			return err
 		}
+
+		conf.FeeRecipientAddrs = def.FeeRecipientAddresses()
+		conf.WithdrawalAddrs = def.WithdrawalAddresses()
+
+		if strings.TrimSpace(def.Name) != "" {
+			conf.Name = def.Name
+		}
```
Comment (corverroos) [inline cmd/createcluster.go:156]: why this conditional?

File: cmd/createcluster.go [hunk 3]
```diff
@@ -152,22 +147,30 @@ func runCreateCluster(ctx context.Context, w io.Writer, conf clusterConfig) erro
 		if err != nil {
 			return err
 		}
+
+		conf.FeeRecipientAddrs = def.FeeRecipientAddresses()
```
Comment (corverroos) [inline cmd/createcluster.go:151]: it feels like definition is the source of truth from this point, why is it required to update the config? The else statement creates a definition from the config, feels like we should just use definition from this point forward

File: cmd/createcluster.go (hunk 2 above)
Comment (gsora) [reply cmd/createcluster.go:156]: removing since as you suggested, definition is source of truth

**Review by corverroos — APPROVED** [review]
